// <auto-generated />
namespace neizlesem_proje.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3003guncel12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3003guncel12));
        
        string IMigrationMetadata.Id
        {
            get { return "202303301338450_30.03guncel12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
