// <auto-generated />
namespace neizlesem_proje.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class guncel3456 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(guncel3456));
        
        string IMigrationMetadata.Id
        {
            get { return "202303242151403_guncel3456"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
