// <auto-generated />
namespace neizlesem_proje.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _30032023guncel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_30032023guncel));
        
        string IMigrationMetadata.Id
        {
            get { return "202303301410558_30.03.2023guncel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
