// <auto-generated />
namespace neizlesem_proje.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class guncel345 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(guncel345));
        
        string IMigrationMetadata.Id
        {
            get { return "202303160855275_guncel345"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
